//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string ExitControlItem {
            get {
                return ResourceManager.GetString("ExitControlItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать игру.
        /// </summary>
        internal static string GameControlItem {
            get {
                return ResourceManager.GetString("GameControlItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tough Growth - это мир геометрических фигур, в котором вы являетесь квадратом. 
        ///Чтобы выиграть нужно стать больше остальных фигур, которые находятся на поле, и съесть их. 
        ///Но нужно быть осторожнее, ведь большие по размеру фигуры будут выдавать различные препятствия 
        ///и сами фигуры будут являться препятствиями. 
        ///При столкновении с ними наступит смерть. ПРЕДУПРЕЖДЕНИЕ: Есть можно только жёлтые фигуры!!! 
        ///
        ///В игре есть 10 уровней. Задача игрока – пройти все уровни игры и набрать наименьшее количество «смер [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GameRules {
            get {
                return ResourceManager.GetString("GameRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string InfoControlItem {
            get {
                return ResourceManager.GetString("InfoControlItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (50;450) 625
        ///ПСК (900;70) 400
        ///КВ (300;250) 1600
        ///КВ (600;150) 2500.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (475;250) 625
        ///ПСК (800;50) 400
        ///П (507;100) 900 (330;100) (507;100) 1
        ///П (330;383) 900 (330;383) (507;383) 1
        ///П (300;100) 800 (300;100) (300;300) -1
        ///П (630;300) 800 (630;100) (630;300) -1.
        /// </summary>
        internal static string Level10 {
            get {
                return ResourceManager.GetString("Level10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (50;450) 625
        ///ПСК (900;70) 400
        ///Ш (500;230) 900.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (50;450) 625
        ///ПСК (900;70) 400
        ///КР (460;230) 2500.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (900;450) 625
        ///ПСК (50;50) 400
        ///Ш (500;230) 900
        ///Ш (690;150) 900
        ///Ш (310;300) 900.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (900;450) 625
        ///ПСК (50;50) 400
        ///КР (900;50) 2500
        ///Ш (600;200) 400
        ///КВ (575;110) 2500
        ///КВ (575;240) 2500
        ///КВ (510;180) 2500
        ///КВ (640;180) 2500
        ///Ш (230;295) 400
        ///КВ (140;275) 2500
        ///КВ (270;275) 2500
        ///КВ (205;210) 2500
        ///КВ (205;340) 2500.
        /// </summary>
        internal static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (475;250) 625
        ///ПСК (50;50) 400
        ///КР (475;30) 2500
        ///КР (900;210) 2500
        ///КР (475;410) 2500
        ///КР (30;210) 2500.
        /// </summary>
        internal static string Level6 {
            get {
                return ResourceManager.GetString("Level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (900;450) 625
        ///ПСК (50;50) 400
        ///Ш (500;230) 900
        ///Т (690;150) 1600
        ///Т (310;300) 1600.
        /// </summary>
        internal static string Level7 {
            get {
                return ResourceManager.GetString("Level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (900;450) 625
        ///ПСК (50;50) 400
        ///Ш (300;400) 900
        ///Т (300;200) 1600
        ///Т (700;300) 1600
        ///КР (675;90) 2500.
        /// </summary>
        internal static string Level8 {
            get {
                return ResourceManager.GetString("Level8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК (50;450) 625
        ///ПСК (900;70) 400
        ///КР (460;230) 2500
        ///Ш (180;150) 800
        ///Т (70;70) 900
        ///П (30;245) 900 (30;245) (300;245) 1
        ///П (820;245) 900 (540;245) (820;245) 1
        ///П (475;100) 800 (475;20) (475;100) -1.
        /// </summary>
        internal static string Level9 {
            get {
                return ResourceManager.GetString("Level9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../Model/Properties/Level.
        /// </summary>
        internal static string LevelsFilesPath {
            get {
                return ResourceManager.GetString("LevelsFilesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главное меню.
        /// </summary>
        internal static string MainMenuControlItem {
            get {
                return ResourceManager.GetString("MainMenuControlItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление меню осуществляется с помощью стрелок клавиатуры &quot;Вверх&quot;, &quot;Вниз&quot;.
        ///С помощью этих клавиш происходит переключение фокуса мажду пунктами меню.
        ///Подтверждение перехода осуществляется с помощью клавиши Enter.
        ///Во время игры управление происходит с помощью стрелок клавиатуры:
        ///&quot;Вверх&quot;, &quot;Вниз&quot;, &quot;Вправо&quot;, &quot;Влево&quot;.
        ///Достаточно нажать и отпутить клавишу и игровой квадрат начнёт двигаться в нужную сторону,
        ///пока не будет нажата стрелка другого направления..
        /// </summary>
        internal static string ManagementRules {
            get {
                return ResourceManager.GetString("ManagementRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекорды.
        /// </summary>
        internal static string RecordsControlItem {
            get {
                return ResourceManager.GetString("RecordsControlItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TOUGH GROWTH.
        /// </summary>
        internal static string TitlePassiveItem {
            get {
                return ResourceManager.GetString("TitlePassiveItem", resourceCulture);
            }
        }
    }
}
